### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by jens-daniel-mueller** [daranzolin/quickglobe#1]
Hi David,
tried your package and it looks great!
Compared to your code in the readme I had to change:
`devtools::install_github("daranzolin/quickglobe")`
and add 
`library(tidyverse)`
in order to make it work from a clean R Skript.
Maybe you want to update this for future new users.
Cheers! Jens

**Comment by daranzolin** [comment]
Ah, thanks for letting me know! Fixed.
